import "./globals.css";
import Navbar from "@/components/navbar/navbar";
import Footer from "@/components/footer/footer";
import localFont from "next/font/local";

const pretendard = localFont({
  src: [
    {
      path: "./fonts/PretendardVariable.woff2",
    },
  ],
  display: "swap",
});

export const metadata = {
  title: "ClusterKice",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="ko">
      <body className={pretendard.className}>
        <header className="header">
          <Navbar />
        </header>
        {children}
        <footer className="footer">
          <Footer />
        </footer>
      </body>
    </html>
  );
}
